version: '3'

services:
  php:
    container_name: composer_docker-php
    build:
      context: ./docker_images
      dockerfile: php.8.1.dockerfile
    volumes:
      - ./src:/home/composer_docker/src
      - composer_docker_home_volume:/home/composer_docker
    working_dir: /home/composer_docker/src

volumes:
  composer_docker_home_volume: null

